### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by zbejas** [NesCafe62/screeps-pathfinding#3]
Hello. I was wondering if you were able to get this to support TypeScript like Traveler. I have tried to bring it into my typescript codebase but I keep getting `Could not find a declaration file for module` errors when trying to import Pathings with `import Pathing from "./lib/pathing/pathing";`

Using `import "./lib/pathing/pathing";` works fine, draws the visuals, but then there is no way to run the moves using `Pathing.runMoves()`

I would also be happy with a few pointers on how I could get this to work as intended here, if possible.

**Comment by zbejas** [comment]
I have figured out i had to add
`checkJs`to my tsconfig for this error to disappear.

**Comment by NesCafe62** [comment]
wow. very cool you got it working. actually I planned to make TS version, even strated with it, but had some struggles. maybe I could do it if someone would help me

**Comment by zbejas** [comment]
> wow. very cool you got it working. actually I planned to make TS version, even strated with it, but had some struggles. maybe I could do it if someone would help me

I am quite new to TS, so I don't know if I would be of much help, but for anyone wanting to import it:

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "esnext",
    "lib": [
      "es2018"
    ],
    "target": "es2018",
    "moduleResolution": "Node",
    "outDir": "dist",
    "baseUrl": "src/",
    "sourceMap": true,
    "strict": true,
    "experimentalDecorators": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "allowJs": true,
    "checkJs": false,
  },
  "exclude": [
    "node_modules"
  ]
}
```

And then just add `import Pathing from "lib/pathing/pathing";`.
VSCode also recommended to change import in pathing.js to `import { logError, isPosEqual, offsetPosCoords, isCoordsEqual, isPosExit, getRange, hasActiveBodyparts, getDirection, posToCoords, lookInRange } from './pathing.utils';`

Last, you need to add you own options to index.d.ts:
```
// ! Pathing

interface TravelToOptions {
    range?: number;
    priority?: number;
    moveOffExit?: boolean;
    moveOffRoad?: boolean;
    moveOffContainer?: boolean;
    visualizePathStyle?: {} | undefined;
    avoidRooms?: string[];
    //findRoute?: (roomName: string, viaRoomName: string) => number;
    offRoads?: boolean;
    ignoreStructures?: boolean;
    ignoreRoads?: boolean;
    ignoreCreeps?: boolean;
    ignoreTunnnels?: boolean;
    ignoreContainers?: boolean;
    plainCost?: number;
    swampCost?: number;
    containerCost?: number;
    costCallback?: (roomName: string, costMatrix: CostMatrix) => void;
    routeCallback?: (roomName: string, fromRoomName: string) => number;
    heuristicWeight?: number;
    fixPath?: boolean;
    allowIncomplete?: boolean;
    maxOps?: number;
    maxRooms?: number;
    maxCost?: number;
    flee?: boolean;
}

```
__Note that not all of the options are in my index.d.ts__

Hope this helped, If you have any other questions, please ask.
